Testing workflows - Again

diff --git a/.github/workflows/sim.yml b/.github/workflows/sim.yml
--- a/.github/workflows/sim.yml
+++ b/.github/workflows/sim.yml
@@ -4,23 +4,23 @@ on: [push, pull_request]
 
 jobs:
   build:
-      runs-on: ubuntu-latest
-      container: wpilib/roborio-cross-ubuntu:2024-22.04
-      steps:
-          - uses: actions/checkout@v4
-          - name: Grant execute permission # just in case
-            run: chmod +x gradlew
-          - name: Compile robot code
-            run: ./gradlew build
-          - name: Run WPILib simulation
-            id: simulation
-            run: |
-              timeout 10s ./gradlew simulateJava || true
-              exit_code=$?
-              if [ $exit_code -eq 124 ]; then
-                echo "The command timed out"
-                exit 0
-              elif [ $exit_code -ne 0 ]; then
-                echo "The command failed"
-                exit $exit_code
-              fi
+    runs-on: ubuntu-latest
+    container: wpilib/roborio-cross-ubuntu:2024-22.04
+    steps:
+      - uses: actions/checkout@v4
+      - name: Grant execute permission # just in case
+        run: chmod +x gradlew
+      - name: Compile robot code
+        run: ./gradlew build
+      - name: Run WPILib simulation
+        id: simulation
+        run: |
+          timeout 10s ./gradlew simulateJava || true
+          exit_code=$?
+          if [ $exit_code -eq 124 ]; then
+            echo "The command timed out (success)"
+            exit 0
+          else
+            echo "The command ended before timeout (failure)"
+            exit 1  # Exit with a failure code
+          fi
